### ISSUE TITLE
password to [hidetoolz.7z](https://github.com/trietptm/HideToolz-Archive/raw/master/hidetoolz.7z)

### ISSUE THREAD

**Issue by evandrix** [trietptm/HideToolz-Archive#1]
what is it? it's not "infected"

**Comment by nachoace** [comment]
Which is the password please?

**Comment by gavz** [comment]
passwd: Fyyre

**Comment by evandrix** [comment]
[hidetoolz.zip](https://github.com/trietptm/HideToolz-Archive/files/6209395/hidetoolz.zip)
